name: Code check & Release

on:
    push:
        branches: [ main ]
    pull_request:
        branches: [ main ]
        types: [ opened, synchronize ]

jobs:
    code-check:
        name: Code check
        runs-on: ubuntu-latest
        if: ${{ github.event_name == 'pull_request' }}
        permissions:
            contents: 'read'
            id-token: 'write'
        steps:
            -   name: Checkout
                uses: actions/checkout@v3

            -   name: Setup Volta
                uses: volta-cli/action@v4
                with:
                    registry-url: 'https://registry.npmjs.org'

            -   name: Install dependencies
                run: yarn install --immutable

            -   name: Lint
                run: yarn lint

    release:
        name: Release
        runs-on: ubuntu-latest
        if: ${{ github.event_name == 'push' }}
        permissions:
            contents: 'write'
            id-token: 'write'
            issues: 'write'
            pull-requests: 'write'
        steps:
            -   name: Checkout
                uses: actions/checkout@v3

            -   name: Setup Volta
                uses: volta-cli/action@v4
                with:
                    registry-url: 'https://registry.npmjs.org'

            -   name: Configure Git User
                run: |
                    git config --global user.email "development@mariomh.com"
                    git config --global user.name "$GITHUB_ACTOR"

            -   name: Echo .npmrc
                run: echo "$(<.npmrc )"

            -   name: Echo other .npmrc
                run: echo "$(</home/runner/work/_temp/.npmrc )"

            -   name: Install dependencies
                run: yarn install --immutable

            -   name: Create Release Pull Request or Publish to npm
                uses: changesets/action@v1
                with:
                    publish: yarn publish
                    version: yarn version
                    commit: 'chore: release'
                    title: 'chore: release'
                    setupGitUser: false
                env:
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                    NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
